### ISSUE TITLE
where is .sql files

### ISSUE THREAD

**Issue by baur** [ranapartap/Micro#1]
> Create the required SQL database/tables with .sql statements in the _install/-folder

there is no such folder and files

**Comment by ranapartap** [comment]
Hi,

_install/micro.sql is added

I have started the project just a few days ago and intentionally skipped the sql files because there is lot of still to add. The basic operations are working fine. 

Recently started a new module to create dynamic pages from admin panel to create a basic and quick application. You can disable this menu from config/menus.php just remove the  "Posts" =>  [] array
 
Thank you.
